test_json = {"city": {"id": 5746545, "name": "Portland",
                      "coord": {"lon": -122.676208, "lat": 45.523449},
                      "country": "US", "population": 0,
                      "sys": {"population": 0}}, "cod": "200",
             "message": 0.0036, "cnt": 40, "list": [{"dt": 1466132400,
                                                     "main": {"temp": 288.2,
                                                              "temp_min": 284.887,
                                                              "temp_max": 288.2,
                                                              "pressure": 999.34,
                                                              "sea_level": 1034.12,
                                                              "grnd_level": 999.34,
                                                              "humidity": 88,
                                                              "temp_kf": 3.31},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 0.02,
                                                              "deg": 254},
                                                     "rain": {"3h": 0.5625},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-17 03:00:00"},
                                                    {"dt": 1466143200,
                                                     "main": {"temp": 283.6,
                                                              "temp_min": 280.472,
                                                              "temp_max": 283.6,
                                                              "pressure": 999.49,
                                                              "sea_level": 1034.65,
                                                              "grnd_level": 999.49,
                                                              "humidity": 96,
                                                              "temp_kf": 3.13},
                                                     "weather": [{"id": 803,
                                                                  "main": "Clouds",
                                                                  "description": "broken clouds",
                                                                  "icon": "04n"}],
                                                     "clouds": {"all": 56},
                                                     "wind": {"speed": 0.67,
                                                              "deg": 34.002},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-17 06:00:00"},
                                                    {"dt": 1466154000,
                                                     "main": {"temp": 281.49,
                                                              "temp_min": 278.541,
                                                              "temp_max": 281.49,
                                                              "pressure": 998.86,
                                                              "sea_level": 1034.13,
                                                              "grnd_level": 998.86,
                                                              "humidity": 92,
                                                              "temp_kf": 2.94},
                                                     "weather": [{"id": 801,
                                                                  "main": "Clouds",
                                                                  "description": "few clouds",
                                                                  "icon": "02n"}],
                                                     "clouds": {"all": 24},
                                                     "wind": {"speed": 0.26,
                                                              "deg": 149.002},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-17 09:00:00"},
                                                    {"dt": 1466164800,
                                                     "main": {"temp": 282.16,
                                                              "temp_min": 279.396,
                                                              "temp_max": 282.16,
                                                              "pressure": 998.74,
                                                              "sea_level": 1033.96,
                                                              "grnd_level": 998.74,
                                                              "humidity": 99,
                                                              "temp_kf": 2.76},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10n"}],
                                                     "clouds": {"all": 100},
                                                     "wind": {"speed": 1.06,
                                                              "deg": 145.001},
                                                     "rain": {"3h": 1.7675},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-17 12:00:00"},
                                                    {"dt": 1466175600,
                                                     "main": {"temp": 284.79,
                                                              "temp_min": 282.211,
                                                              "temp_max": 284.79,
                                                              "pressure": 998.62,
                                                              "sea_level": 1033.84,
                                                              "grnd_level": 998.62,
                                                              "humidity": 100,
                                                              "temp_kf": 2.58},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10d"}],
                                                     "clouds": {"all": 80},
                                                     "wind": {"speed": 1.15,
                                                              "deg": 36.5035},
                                                     "rain": {"3h": 0.82},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-17 15:00:00"},
                                                    {"dt": 1466186400,
                                                     "main": {"temp": 286.45,
                                                              "temp_min": 284.056,
                                                              "temp_max": 286.45,
                                                              "pressure": 998.51,
                                                              "sea_level": 1033.25,
                                                              "grnd_level": 998.51,
                                                              "humidity": 98,
                                                              "temp_kf": 2.39},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10d"}],
                                                     "clouds": {"all": 76},
                                                     "wind": {"speed": 1.36,
                                                              "deg": 324.007},
                                                     "rain": {"3h": 0.965},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-17 18:00:00"},
                                                    {"dt": 1466197200,
                                                     "main": {"temp": 290.52,
                                                              "temp_min": 288.307,
                                                              "temp_max": 290.52,
                                                              "pressure": 997.07,
                                                              "sea_level": 1031.69,
                                                              "grnd_level": 997.07,
                                                              "humidity": 81,
                                                              "temp_kf": 2.21},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10d"}],
                                                     "clouds": {"all": 64},
                                                     "wind": {"speed": 1.63,
                                                              "deg": 313.003},
                                                     "rain": {"3h": 0.035},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-17 21:00:00"},
                                                    {"dt": 1466208000,
                                                     "main": {"temp": 288.56,
                                                              "temp_min": 286.54,
                                                              "temp_max": 288.56,
                                                              "pressure": 997.32,
                                                              "sea_level": 1031.69,
                                                              "grnd_level": 997.32,
                                                              "humidity": 95,
                                                              "temp_kf": 2.02},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10n"}],
                                                     "clouds": {"all": 92},
                                                     "wind": {"speed": 0.51,
                                                              "deg": 251.011},
                                                     "rain": {"3h": 1.075},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-18 00:00:00"},
                                                    {"dt": 1466218800,
                                                     "main": {"temp": 287.06,
                                                              "temp_min": 285.22,
                                                              "temp_max": 287.06,
                                                              "pressure": 998.05,
                                                              "sea_level": 1032.78,
                                                              "grnd_level": 998.05,
                                                              "humidity": 98,
                                                              "temp_kf": 1.84},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10n"}],
                                                     "clouds": {"all": 92},
                                                     "wind": {"speed": 1.06,
                                                              "deg": 176.006},
                                                     "rain": {"3h": 0.695},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-18 03:00:00"},
                                                    {"dt": 1466229600,
                                                     "main": {"temp": 284.69,
                                                              "temp_min": 283.036,
                                                              "temp_max": 284.69,
                                                              "pressure": 999.34,
                                                              "sea_level": 1034.4,
                                                              "grnd_level": 999.34,
                                                              "humidity": 100,
                                                              "temp_kf": 1.66},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10n"}],
                                                     "clouds": {"all": 100},
                                                     "wind": {"speed": 1.06,
                                                              "deg": 265.501},
                                                     "rain": {"3h": 1.175},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-18 06:00:00"},
                                                    {"dt": 1466240400,
                                                     "main": {"temp": 284.02,
                                                              "temp_min": 282.547,
                                                              "temp_max": 284.02,
                                                              "pressure": 999.42,
                                                              "sea_level": 1034.55,
                                                              "grnd_level": 999.42,
                                                              "humidity": 100,
                                                              "temp_kf": 1.47},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10n"}],
                                                     "clouds": {"all": 92},
                                                     "wind": {"speed": 1.21,
                                                              "deg": 231.501},
                                                     "rain": {"3h": 1.075},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-18 09:00:00"},
                                                    {"dt": 1466251200,
                                                     "main": {"temp": 283.1,
                                                              "temp_min": 281.811,
                                                              "temp_max": 283.1,
                                                              "pressure": 1000.7,
                                                              "sea_level": 1035.83,
                                                              "grnd_level": 1000.7,
                                                              "humidity": 100,
                                                              "temp_kf": 1.29},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10n"}],
                                                     "clouds": {"all": 76},
                                                     "wind": {"speed": 1.06,
                                                              "deg": 206.501},
                                                     "rain": {"3h": 1.18},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-18 12:00:00"},
                                                    {"dt": 1466262000,
                                                     "main": {"temp": 284.05,
                                                              "temp_min": 282.948,
                                                              "temp_max": 284.05,
                                                              "pressure": 1002.17,
                                                              "sea_level": 1037.37,
                                                              "grnd_level": 1002.17,
                                                              "humidity": 100,
                                                              "temp_kf": 1.1},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10d"}],
                                                     "clouds": {"all": 56},
                                                     "wind": {"speed": 1.42,
                                                              "deg": 216},
                                                     "rain": {"3h": 0.09},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-18 15:00:00"},
                                                    {"dt": 1466272800,
                                                     "main": {"temp": 286.46,
                                                              "temp_min": 285.536,
                                                              "temp_max": 286.46,
                                                              "pressure": 1003.51,
                                                              "sea_level": 1038.33,
                                                              "grnd_level": 1003.51,
                                                              "humidity": 92,
                                                              "temp_kf": 0.92},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10d"}],
                                                     "clouds": {"all": 56},
                                                     "wind": {"speed": 1.41,
                                                              "deg": 263.505},
                                                     "rain": {"3h": 0.005},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-18 18:00:00"},
                                                    {"dt": 1466283600,
                                                     "main": {"temp": 288.95,
                                                              "temp_min": 288.211,
                                                              "temp_max": 288.95,
                                                              "pressure": 1004.19,
                                                              "sea_level": 1038.93,
                                                              "grnd_level": 1004.19,
                                                              "humidity": 73,
                                                              "temp_kf": 0.74},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10d"}],
                                                     "clouds": {"all": 48},
                                                     "wind": {"speed": 1.62,
                                                              "deg": 290.502},
                                                     "rain": {"3h": 0.055},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-18 21:00:00"},
                                                    {"dt": 1466294400,
                                                     "main": {"temp": 288.24,
                                                              "temp_min": 287.691,
                                                              "temp_max": 288.24,
                                                              "pressure": 1005.62,
                                                              "sea_level": 1040.38,
                                                              "grnd_level": 1005.62,
                                                              "humidity": 69,
                                                              "temp_kf": 0.55},
                                                     "weather": [{"id": 500,
                                                                  "main": "Rain",
                                                                  "description": "light rain",
                                                                  "icon": "10n"}],
                                                     "clouds": {"all": 20},
                                                     "wind": {"speed": 1.62,
                                                              "deg": 316.5},
                                                     "rain": {"3h": 0.005},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-19 00:00:00"},
                                                    {"dt": 1466305200,
                                                     "main": {"temp": 286.66,
                                                              "temp_min": 286.295,
                                                              "temp_max": 286.66,
                                                              "pressure": 1006.92,
                                                              "sea_level": 1041.84,
                                                              "grnd_level": 1006.92,
                                                              "humidity": 68,
                                                              "temp_kf": 0.37},
                                                     "weather": [{"id": 801,
                                                                  "main": "Clouds",
                                                                  "description": "few clouds",
                                                                  "icon": "02n"}],
                                                     "clouds": {"all": 24},
                                                     "wind": {"speed": 1.56,
                                                              "deg": 328.502},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-19 03:00:00"},
                                                    {"dt": 1466316000,
                                                     "main": {"temp": 281.65,
                                                              "temp_min": 281.466,
                                                              "temp_max": 281.65,
                                                              "pressure": 1008.26,
                                                              "sea_level": 1043.53,
                                                              "grnd_level": 1008.26,
                                                              "humidity": 86,
                                                              "temp_kf": 0.18},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.31,
                                                              "deg": 337.503},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-19 06:00:00"},
                                                    {"dt": 1466326800,
                                                     "main": {"temp": 278.688,
                                                              "temp_min": 278.688,
                                                              "temp_max": 278.688,
                                                              "pressure": 1008.79,
                                                              "sea_level": 1044.39,
                                                              "grnd_level": 1008.79,
                                                              "humidity": 92,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.17,
                                                              "deg": 322.501},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-19 09:00:00"},
                                                    {"dt": 1466337600,
                                                     "main": {"temp": 277.088,
                                                              "temp_min": 277.088,
                                                              "temp_max": 277.088,
                                                              "pressure": 1009.34,
                                                              "sea_level": 1045.01,
                                                              "grnd_level": 1009.34,
                                                              "humidity": 90,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 0.7,
                                                              "deg": 328.503},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-19 12:00:00"},
                                                    {"dt": 1466348400,
                                                     "main": {"temp": 283.396,
                                                              "temp_min": 283.396,
                                                              "temp_max": 283.396,
                                                              "pressure": 1010.11,
                                                              "sea_level": 1045.54,
                                                              "grnd_level": 1010.11,
                                                              "humidity": 80,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01d"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 0.7,
                                                              "deg": 85.501},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-19 15:00:00"},
                                                    {"dt": 1466359200,
                                                     "main": {"temp": 288.488,
                                                              "temp_min": 288.488,
                                                              "temp_max": 288.488,
                                                              "pressure": 1010.06,
                                                              "sea_level": 1045.03,
                                                              "grnd_level": 1010.06,
                                                              "humidity": 67,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01d"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.41,
                                                              "deg": 324},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-19 18:00:00"},
                                                    {"dt": 1466370000,
                                                     "main": {"temp": 292.145,
                                                              "temp_min": 292.145,
                                                              "temp_max": 292.145,
                                                              "pressure": 1009,
                                                              "sea_level": 1043.65,
                                                              "grnd_level": 1009,
                                                              "humidity": 59,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01d"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.66,
                                                              "deg": 332.501},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-19 21:00:00"},
                                                    {"dt": 1466380800,
                                                     "main": {"temp": 293.837,
                                                              "temp_min": 293.837,
                                                              "temp_max": 293.837,
                                                              "pressure": 1007.37,
                                                              "sea_level": 1042.03,
                                                              "grnd_level": 1007.37,
                                                              "humidity": 51,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.97,
                                                              "deg": 339.5},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-20 00:00:00"},
                                                    {"dt": 1466391600,
                                                     "main": {"temp": 291.505,
                                                              "temp_min": 291.505,
                                                              "temp_max": 291.505,
                                                              "pressure": 1006.56,
                                                              "sea_level": 1041.32,
                                                              "grnd_level": 1006.56,
                                                              "humidity": 54,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.81,
                                                              "deg": 341.501},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-20 03:00:00"},
                                                    {"dt": 1466402400,
                                                     "main": {"temp": 284.718,
                                                              "temp_min": 284.718,
                                                              "temp_max": 284.718,
                                                              "pressure": 1006.12,
                                                              "sea_level": 1041.29,
                                                              "grnd_level": 1006.12,
                                                              "humidity": 72,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.2,
                                                              "deg": 355.006},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-20 06:00:00"},
                                                    {"dt": 1466413200,
                                                     "main": {"temp": 281.541,
                                                              "temp_min": 281.541,
                                                              "temp_max": 281.541,
                                                              "pressure": 1005.15,
                                                              "sea_level": 1040.52,
                                                              "grnd_level": 1005.15,
                                                              "humidity": 86,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 0.91,
                                                              "deg": 21.0005},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-20 09:00:00"},
                                                    {"dt": 1466424000,
                                                     "main": {"temp": 279.981,
                                                              "temp_min": 279.981,
                                                              "temp_max": 279.981,
                                                              "pressure": 1004.4,
                                                              "sea_level": 1039.87,
                                                              "grnd_level": 1004.4,
                                                              "humidity": 86,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.16,
                                                              "deg": 27.5006},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-20 12:00:00"},
                                                    {"dt": 1466434800,
                                                     "main": {"temp": 287.967,
                                                              "temp_min": 287.967,
                                                              "temp_max": 287.967,
                                                              "pressure": 1003.92,
                                                              "sea_level": 1039.11,
                                                              "grnd_level": 1003.92,
                                                              "humidity": 73,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01d"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.52,
                                                              "deg": 46.5005},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-20 15:00:00"},
                                                    {"dt": 1466445600,
                                                     "main": {"temp": 296.468,
                                                              "temp_min": 296.468,
                                                              "temp_max": 296.468,
                                                              "pressure": 1002.92,
                                                              "sea_level": 1037.62,
                                                              "grnd_level": 1002.92,
                                                              "humidity": 48,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01d"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.96,
                                                              "deg": 58.5013},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-20 18:00:00"},
                                                    {"dt": 1466456400,
                                                     "main": {"temp": 299.806,
                                                              "temp_min": 299.806,
                                                              "temp_max": 299.806,
                                                              "pressure": 1001.31,
                                                              "sea_level": 1035.69,
                                                              "grnd_level": 1001.31,
                                                              "humidity": 35,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01d"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 2.22,
                                                              "deg": 70.0004},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-20 21:00:00"},
                                                    {"dt": 1466467200,
                                                     "main": {"temp": 300.982,
                                                              "temp_min": 300.982,
                                                              "temp_max": 300.982,
                                                              "pressure": 999.41,
                                                              "sea_level": 1033.67,
                                                              "grnd_level": 999.41,
                                                              "humidity": 28,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.96,
                                                              "deg": 56.5016},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-21 00:00:00"},
                                                    {"dt": 1466478000,
                                                     "main": {"temp": 297.445,
                                                              "temp_min": 297.445,
                                                              "temp_max": 297.445,
                                                              "pressure": 998.18,
                                                              "sea_level": 1032.56,
                                                              "grnd_level": 998.18,
                                                              "humidity": 33,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.65,
                                                              "deg": 50.5072},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-21 03:00:00"},
                                                    {"dt": 1466488800,
                                                     "main": {"temp": 288.975,
                                                              "temp_min": 288.975,
                                                              "temp_max": 288.975,
                                                              "pressure": 997.64,
                                                              "sea_level": 1032.35,
                                                              "grnd_level": 997.64,
                                                              "humidity": 40,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.66,
                                                              "deg": 56.0011},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-21 06:00:00"},
                                                    {"dt": 1466499600,
                                                     "main": {"temp": 285.127,
                                                              "temp_min": 285.127,
                                                              "temp_max": 285.127,
                                                              "pressure": 996.2,
                                                              "sea_level": 1031.01,
                                                              "grnd_level": 996.2,
                                                              "humidity": 50,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.36,
                                                              "deg": 53.5024},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-21 09:00:00"},
                                                    {"dt": 1466510400,
                                                     "main": {"temp": 283.829,
                                                              "temp_min": 283.829,
                                                              "temp_max": 283.829,
                                                              "pressure": 994.63,
                                                              "sea_level": 1029.68,
                                                              "grnd_level": 994.63,
                                                              "humidity": 64,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "02n"}],
                                                     "clouds": {"all": 8},
                                                     "wind": {"speed": 1.21,
                                                              "deg": 34.5},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-21 12:00:00"},
                                                    {"dt": 1466521200,
                                                     "main": {"temp": 291.69,
                                                              "temp_min": 291.69,
                                                              "temp_max": 291.69,
                                                              "pressure": 994.09,
                                                              "sea_level": 1028.88,
                                                              "grnd_level": 994.09,
                                                              "humidity": 68,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "02d"}],
                                                     "clouds": {"all": 8},
                                                     "wind": {"speed": 1.15,
                                                              "deg": 39.5024},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-21 15:00:00"},
                                                    {"dt": 1466532000,
                                                     "main": {"temp": 298.791,
                                                              "temp_min": 298.791,
                                                              "temp_max": 298.791,
                                                              "pressure": 993.77,
                                                              "sea_level": 1028.18,
                                                              "grnd_level": 993.77,
                                                              "humidity": 39,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 801,
                                                                  "main": "Clouds",
                                                                  "description": "few clouds",
                                                                  "icon": "02d"}],
                                                     "clouds": {"all": 24},
                                                     "wind": {"speed": 0.86,
                                                              "deg": 313.006},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-21 18:00:00"},
                                                    {"dt": 1466542800,
                                                     "main": {"temp": 300.494,
                                                              "temp_min": 300.494,
                                                              "temp_max": 300.494,
                                                              "pressure": 993.35,
                                                              "sea_level": 1027.27,
                                                              "grnd_level": 993.35,
                                                              "humidity": 35,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 803,
                                                                  "main": "Clouds",
                                                                  "description": "broken clouds",
                                                                  "icon": "04d"}],
                                                     "clouds": {"all": 80},
                                                     "wind": {"speed": 1.63,
                                                              "deg": 275},
                                                     "rain": {},
                                                     "sys": {"pod": "d"},
                                                     "dt_txt": "2016-06-21 21:00:00"},
                                                    {"dt": 1466553600,
                                                     "main": {"temp": 301.007,
                                                              "temp_min": 301.007,
                                                              "temp_max": 301.007,
                                                              "pressure": 992.93,
                                                              "sea_level": 1026.97,
                                                              "grnd_level": 992.93,
                                                              "humidity": 34,
                                                              "temp_kf": 0},
                                                     "weather": [{"id": 800,
                                                                  "main": "Clear",
                                                                  "description": "clear sky",
                                                                  "icon": "01n"}],
                                                     "clouds": {"all": 0},
                                                     "wind": {"speed": 1.95,
                                                              "deg": 280},
                                                     "rain": {},
                                                     "sys": {"pod": "n"},
                                                     "dt_txt": "2016-06-22 00:00:00"}]}
