# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualDayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meas', models.DateField()),
                ('location', models.CharField(max_length=6)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reference', models.DateField()),
                ('day_in_advance', models.IntegerField()),
                ('source', models.CharField(max_length=6)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateField()),
                ('date_covers', models.DateField()),
                ('source', models.CharField(max_length=6)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
            ],
        ),
    ]
