# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualDayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meas', models.DateField()),
                ('location', models.CharField(max_length=6)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reference', models.DateField()),
                ('day_in_advance', models.IntegerField()),
                ('source', models.CharField(max_length=6)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorHistogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=6)),
                ('location', models.CharField(max_length=6)),
                ('type', models.CharField(max_length=6)),
                ('day_in_advance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='errorbin',
            name='member_of_hist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_maniac.ErrorHistogram'),
        ),
    ]
